apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 964215206189.dkr.ecr.ap-south-1.amazonaws.com/myrepo:master-980bac0d84775f41173d418958072ce4c067fc90
          ports:
            - containerPort: 80
